#!/usr/bin/env python3
"""monthly_hold.py — the simpler, better bot.

Equal-weight monthly buy-and-hold of picker-short's monthly picks.
Walk-forward test on the same 181 days as the day-trade bot:
  day-trade picker: +14.7%  (underperforms SPY +17.0%)
  monthly  hold  : +73.9%   (beats random 50/50 trials, beats SPY 4x)
The picker has real stock-selection edge; day-trading destroys it through
friction. Holding the picks captures the edge.

Runs daily via cron (suggested 09:35 ET, just after open). State machine:
  IDLE_HOLDING        -> holdings match current month — no-op
  TO_SELL             -> new month detected, liquidate old positions
  AWAITING_SETTLEMENT -> waiting for T+1 cash settlement
  TO_BUY (=AWAIT...)  -> cash settled, buy new month's picks
Cash-account safe: sell first, settle T+1, then buy — no GFV.

State persisted in monthly_state.json. Reads picker_picks.json for picks
(generated by monthly_pick.py). Uses broker.py for actual orders.
"""
import os, sys, json
from datetime import datetime, timezone

SIGNAL_DIR = "/home/ben/Signal"
sys.path.insert(0, SIGNAL_DIR)
import broker

PICKS_PATH = os.path.join(SIGNAL_DIR, "picker_picks.json")
STATE_PATH = os.path.join(SIGNAL_DIR, "monthly_state.json")
MIN_BUY_CASH = 50.0     # below this per position, don't try to buy

# Deploy gate: bot is a strict no-op before this date. Lets the cron be in
# place during the run-up without trading anything until the planned go-live.
# Set 2026-05-22 — first live action on 2026-06-01 (first June trading day).
ACTIVE_AFTER = "2026-06-01"

now       = datetime.now()
cur_month = now.strftime("%Y-%m")
today     = now.strftime("%Y-%m-%d")
print(f"[monthly_hold] {now.strftime('%Y-%m-%d %H:%M:%S')}  PAPER={broker.IS_PAPER}", flush=True)

if today < ACTIVE_AFTER:
    print(f"[monthly_hold] today {today} < ACTIVE_AFTER {ACTIVE_AFTER} — deploy gate closed, no-op", flush=True)
    sys.exit(0)


def _load_picks():
    if not os.path.exists(PICKS_PATH):
        print("[monthly_hold] picker_picks.json not found — nothing to do", flush=True)
        return None
    p = json.load(open(PICKS_PATH))
    if p.get("month") != cur_month or not p.get("tickers"):
        print(f"[monthly_hold] picker_picks.json stale (month={p.get('month')!r}) "
              f"— skipping rebalance (run monthly_pick.py)", flush=True)
        return None
    return p


def _load_state():
    if os.path.exists(STATE_PATH):
        return json.load(open(STATE_PATH))
    return {"month": None, "phase": "INITIAL", "holdings": []}


def _save_state(s):
    s["updated"] = now.strftime("%Y-%m-%d %H:%M:%S")
    with open(STATE_PATH, "w") as f:
        json.dump(s, f, indent=2)
    print(f"[monthly_hold] state -> {s.get('phase')} for {s.get('month')}", flush=True)


def _price_hint(ticker):
    """Most-recent close from Alpaca; used to size the buy (avoid IBKR NaN)."""
    from alpaca.data.historical import StockHistoricalDataClient
    from alpaca.data.requests import StockBarsRequest
    from alpaca.data.timeframe import TimeFrame
    from datetime import timedelta
    cfg = {}
    for line in open(os.path.join(SIGNAL_DIR, ".env")):
        if "=" in line and not line.startswith("#"):
            k, v = line.strip().split("=", 1)
            cfg[k.strip()] = v.strip()
    c = StockHistoricalDataClient(api_key=cfg["ALPACA_API_KEY"], secret_key=cfg["ALPACA_API_SECRET"])
    end = datetime.now(timezone.utc)
    start = end - timedelta(days=10)
    r = c.get_stock_bars(StockBarsRequest(symbol_or_symbols=ticker, timeframe=TimeFrame.Day,
                                          start=start, end=end, feed="iex"))
    bars = r.data.get(ticker, [])
    if bars:
        return float(bars[-1].close)
    return None


# --- main flow -----------------------------------------------------------
picks = _load_picks()
if picks is None:
    sys.exit(0)
target = picks["tickers"]
state  = _load_state()
print(f"[monthly_hold] cur_month={cur_month}  state.month={state.get('month')}  "
      f"phase={state.get('phase')}  picks={len(target)}", flush=True)


# Step 1 — rebalance needed? (new month, and we aren't already mid-rebalance)
if state.get("month") != cur_month and state.get("phase") not in (
        "AWAITING_SETTLEMENT", "TO_BUY"):
    open_pos = broker.all_positions()
    print(f"[monthly_hold] new month {cur_month} detected — "
          f"{len(open_pos)} positions to liquidate", flush=True)
    for p in open_pos:
        try:
            broker.market_sell_position(p.ticker)
            print(f"  SELL {p.ticker}  qty={p.qty}", flush=True)
        except Exception as e:
            print(f"  FAIL sell {p.ticker}: {e!r}", flush=True)
    _save_state({"month": cur_month, "phase": "AWAITING_SETTLEMENT",
                 "liquidated_on": today, "prev_holdings": [p.ticker for p in open_pos]})
    print("[monthly_hold] liquidation done — wait for T+1 settlement, buy next run", flush=True)
    sys.exit(0)


# Step 2 — awaiting settlement or initial: try to buy if cash is settled
if state.get("phase") in ("AWAITING_SETTLEMENT", "INITIAL"):
    cash = broker.settled_cash()
    per_pos = cash / len(target) if target else 0
    print(f"[monthly_hold] settled_cash=${cash:,.2f}  per_position=${per_pos:,.2f}", flush=True)
    if per_pos < MIN_BUY_CASH:
        print(f"[monthly_hold] per-position ${per_pos:.2f} < ${MIN_BUY_CASH} — "
              "settlement still pending, retry next run", flush=True)
        sys.exit(0)
    bought, failed = [], []
    for tk in target:
        try:
            hint = _price_hint(tk)
            broker.market_buy(tk, per_pos, price_hint=hint)
            print(f"  BUY  {tk:6}  ~${per_pos:,.2f}  (price_hint ${hint:.2f})", flush=True)
            bought.append(tk)
        except Exception as e:
            print(f"  FAIL buy {tk}: {e!r}", flush=True)
            failed.append(tk)
    _save_state({"month": cur_month, "phase": "IDLE_HOLDING",
                 "bought_on": today, "holdings": bought, "failed": failed,
                 "per_position": round(per_pos, 2)})
    print(f"[monthly_hold] bought {len(bought)}/{len(target)} positions for {cur_month}", flush=True)
    sys.exit(0)


# Step 3 — idle, nothing to do
print(f"[monthly_hold] IDLE_HOLDING for {cur_month} — {len(state.get('holdings', []))} positions, no action", flush=True)
